### ISSUE TITLE
Was the Font AHG reestabalished? 

### ISSUE THREAD

**Issue by murata2makoto** [MPEGGroup/OpenFontFormat#23]
If it is reestablished, what is the charter?  Who can join it?

**Comment by alerque** [comment]
As [commented](https://github.com/MPEGGroup/OpenFontFormat/issues/22#issuecomment-714095999) by @mpsuzuki:

> SC29/WG3 reestablished the Font AHG, the invited experts (even if they are not the member of some national body delegates) may be included.

Also relevant would be the AHG report as submitted by Vlad to the SC/WG which was attached to a mailing list post. Section V reads:

> **AHG Recommendations**
> The AHG recommends that the newly established GitHub repository “[MPEGGroup/OpenFontFormat](https://github.com/MPEGGroup/OpenFontFormat)” should be recognized as an officially sanctioned venue for technical discussions and issue tracking, with the understanding that all final proposals that the AHG intends to submit as input contributions to the WG should be made available for review on the AHG email list.
> The AHG also recommends continuing exploration activities and discussions of the technical issues raised by the CSS WG and newly formed Font and Text CG. We invite the participation of their experts to help us propose and develop solutions that would become parts of the future amendment of the ISO/IEC 14496-22:2019.

Given no announcement of change was made to the list and the confirmation of reestablishment above, I would presume the charter remains at least substantially unchanged. I think it's safe to assume there are (still) zero restrictions on who can or cannot participate in the AHG.

Official word on the response to that first recommendation would be nice to have in writing somewhere. Presumably it appears in meeting minutes somewhere. As I understand it you Murata are more likely to be able to find that than I given the limited access to SC/WG documents. I'm sure Vlad will confirm here or on the email list eventually as well.

**Comment by murata2makoto** [comment]
I will wait for the official announcement of SC29.

**Comment by vlevantovsky** [comment]
I sent the announcement to the AHG email list. The output document announcing the establishment of the WG3 AHGs has not yet been published, I will follow up with the link as soon as it's available.

**Comment by alerque** [comment]
@vlevantovsky Part of the benefit of an issue *tracker* is that the status of issues can be used to track their resolution. For that to be effective the status needs to reflect the actual current status. In this case the issue is not yet fully resolved and the issue shouldn't be closed. Even if a specific outcome is anticipated (and I'm sure you internally have a todo-list that will remind you) the outcome isn't public yet. The time to close this would be when the link to the output document is posted.

**Comment by vlevantovsky** [comment]
The establishment of the AHG, the mandates that have been approved by the WG, and the SC29 document publication timeline are not subjects for the AHG discussions. Our use of this GitHub repository have been authorized for technical discussions only, the procedural matters (if they are within the scope of the established mandates) should be discussed on the AHG email list.
The original question, raised when this issue was opened, is answered by [my email message to the AHG list](https://lists.aau.at/pipermail/mpeg-otspec/2020-October/002656.html)
